<?xml version="1.0" encoding="utf-8"?><Database Name="QL_NHANSU" Class="DataTaiKhoanDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-Q6N4J46\SQLEXPRESS;Initial Catalog=QL_NHANSU;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QL_NHANSUConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="MANV" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKHAU" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>